sudo: false
language: node_js
node_js:
  - "8"
script:
  - npm test
after_success:
  - npm run coverage
notifications:
  slack:
    rooms:
      - secure: Pk10Sp7noDB+tjs1MyXP2psq6qaoHYqJJPdFjK+AY5P2HhFQQE63sxNt8urclCutc9N1jWRWt5PDeJD1CeoOWf2K0dtLECuBZdYAL+Yh1NRLmsrszHzq+rf9E3XMd4ww+W8lIWRbcFBGCypP3Zqs4CUjd79HzaJqjX6v6i7vp3NEeuD5KmPAC0b7oUKxkm/G0VTe6fMsV3DRniD0BBrWnasXgRZf69XJJJp1Vpx61eWGz3+Ab2/TvgfwjyAu3CiEIJEjQarHHAw6f6Co67qLpIyMymtm4jOOCybZWz300E6r58lKWUqT3f6sOaGk1Nb1oGtqNBFK2nWg9ir0Ko2VgiutAAKVyUa3xfyll9sPVlB+Nk/RJF2xulc7/zs3mr8Qzcqv9aagMreglshdMJt6RRz8ZA6550j0cGeg1Vr2cgLJgLHS5EXxBOfpUP8IzG9b+nJOryLlqfcwOeE7yXM+a7cbjyPMp7datcVQXUDRvHmDI3IO5s/E1unnzMznONx5GRLiQgO4mF/iJIaR+OpZbgAA2UldvhnKrtKamdW0XDoOBCn08sNARyp7EJNRFXNuOdftqbs8wlZufXc0yiIFLT/wf2k/yaRQ0H4yYQtJpm6cKvhltDiFHb9rzLoPumuHy0fmpx/8f6kOvW0Q35A2Al/tUt/PqyvtrDCbMeDlfuI=
    on_success: change
